### ISSUE TITLE
Failed to execute the webpack script

### ISSUE THREAD

**Issue by BkSouX** [JustClear/blurify#5]
Hi,

I have an issue when running the webpack script.

```
webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
```

I cloned the project, did a npm install and npm run prod:webpack.
Do you know why ?

**Comment by JustClear** [comment]
You may update the `.babelrc` file like this:

```json
{
    "presets": ["es2015"],
    "plugins": [
        "transform-object-rest-spread"
    ]
}

```
